# Generated by Django 5.0.3 on 2024-06-01 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0004_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('alumniID', models.AutoField(primary_key=True, serialize=False)),
                ('alumnidate', models.DateField()),
                ('alumnibirthday', models.DateField()),
                ('alumnicontact', models.CharField(max_length=15)),
                ('sssgsis', models.CharField(max_length=20)),
                ('tin', models.CharField(max_length=20)),
                ('parentguardian', models.CharField(max_length=100)),
                ('alumniaddress', models.TextField()),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('email_add', models.CharField(default='', max_length=100)),
                ('degree', models.CharField(default='', max_length=100)),
                ('sex', models.CharField(default='', max_length=10)),
                ('claimed_date', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentLife_system.studentinfo')),
            ],
        ),
    ]
