# Generated by Django 5.0.3 on 2024-06-01 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0005_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='graduateForm',
            fields=[
                ('alumniID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studentLife_system.alumni')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('degree', models.CharField(default='', max_length=100)),
                ('sex', models.CharField(default='', max_length=10)),
                ('email_add', models.CharField(default='', max_length=100)),
                ('contactnum', models.CharField(default='', max_length=100)),
                ('alumniaddress', models.CharField(max_length=255)),
                ('dategraduated', models.DateField()),
                ('nameoforganization', models.CharField(max_length=255)),
                ('employmenttype', models.CharField(default='default_value_here', max_length=100)),
                ('occupationalClass', models.CharField(max_length=100)),
                ('gradscholrelated', models.CharField(max_length=10)),
                ('yearscompany', models.CharField(max_length=20)),
                ('placework', models.CharField(max_length=100)),
                ('firstjobgraduate', models.CharField(max_length=10)),
                ('reasonstayingjob', models.TextField()),
                ('designation', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('monthlyincome', models.CharField(max_length=50)),
                ('workwhileworking', models.CharField(max_length=10)),
                ('ifnotworking', models.CharField(max_length=255)),
                ('reasontimegap', models.TextField()),
                ('natureemployment', models.CharField(max_length=100)),
                ('numberofyears', models.CharField(max_length=20)),
                ('monthlyincome2', models.CharField(max_length=50)),
                ('academicprofession', models.IntegerField()),
                ('researchcapability', models.IntegerField()),
                ('learningefficiency', models.IntegerField()),
                ('peopleskills', models.IntegerField()),
                ('problemsolvingskills', models.IntegerField()),
                ('informationtechnologyskills', models.IntegerField()),
                ('communityfield', models.IntegerField()),
                ('globalfield', models.IntegerField()),
                ('criticalskills', models.IntegerField()),
                ('salaryimprovement', models.IntegerField()),
                ('opportunitiesabroad', models.IntegerField()),
                ('personalitydevelopment', models.IntegerField()),
                ('technologiesvaluesformation', models.IntegerField()),
                ('meetingprofessionalneeds', models.CharField(default='', max_length=100)),
                ('rangeofcourses', models.CharField(max_length=100)),
                ('relevanceprofession', models.CharField(max_length=100)),
                ('extracurricular', models.CharField(max_length=100)),
                ('premiumresearch', models.CharField(max_length=100, null=True)),
                ('interlearning', models.CharField(max_length=100)),
                ('teachingenvironment', models.CharField(max_length=100)),
                ('qualityinstruction', models.CharField(max_length=100)),
                ('teachrelationship', models.CharField(max_length=100)),
                ('libraryresources', models.CharField(max_length=100)),
                ('labresources', models.CharField(max_length=100)),
                ('classize', models.CharField(max_length=100)),
                ('profexpertise', models.CharField(max_length=100)),
                ('profsubjectmatter', models.CharField(max_length=100)),
                ('enrollmentdate', models.DateField()),
                ('studiesdegree', models.CharField(max_length=100)),
                ('universityinstitution', models.CharField(max_length=255)),
                ('studiesAddress', models.CharField(max_length=255)),
                ('pursuingstudies', models.TextField()),
                ('student', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='studentLife_system.studentinfo')),
            ],
        ),
    ]
