# Generated by Django 5.0.3 on 2024-06-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0008_jobfair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yearbook',
            fields=[
                ('yearbookID', models.AutoField(primary_key=True, serialize=False)),
                ('yearbookFirstname', models.CharField(max_length=100)),
                ('yearbookLastname', models.CharField(max_length=100)),
                ('yearbookAddress', models.CharField(max_length=255)),
                ('yearbookCourse', models.CharField(max_length=100)),
                ('yearbookImage', models.ImageField(upload_to='yearbook_images/')),
                ('yearbookGender', models.CharField(default='', max_length=100)),
                ('yearbookYearGrad', models.IntegerField(default=0)),
            ],
        ),
    ]
