# Generated by Django 4.2.11 on 2024-06-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0005_mod_program_project'),
        ('studentLife_system', '0009_yearbook'),
    ]

    operations = [
    ]
