# Generated by Django 5.0.6 on 2024-06-03 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0011_fileuploadtest_individualprofilebasicinfo_testarray_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeinverview',
            name='intakeId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intakeinverview',
            name='individualProfileId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentLife_system.individualprofilebasicinfo'),
        ),
    ]
