# Generated by Django 4.2.11 on 2024-06-03 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0011_fileuploadtest_individualprofilebasicinfo_testarray_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='date_time',
        ),
        migrations.AddField(
            model_name='mod',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
