# Generated by Django 5.0.3 on 2024-06-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0013_guidancetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfair',
            name='applicationdeadline',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='posted_date',
            field=models.DateField(default=None),
        ),
    ]
