# Generated by Django 4.2.11 on 2024-06-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0012_remove_mod_date_time_mod_date'),
        ('studentLife_system', '0014_jobfair_applicationdeadline_jobfair_posted_date'),
    ]

    operations = [
    ]
