# Generated by Django 5.0.4 on 2024-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0016_alter_jobfair_applicationdeadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='image_details',
            field=models.ImageField(default=None, upload_to='images/gcash_details/'),
        ),
    ]
