# Generated by Django 4.2.11 on 2024-06-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0024_alter_mod_image_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrDonation',
            fields=[
                ('qr_id', models.AutoField(primary_key=True, serialize=False)),
                ('gcash', models.ImageField(upload_to='images/')),
                ('bpi', models.ImageField(upload_to='images/')),
                ('bdo', models.ImageField(upload_to='images/')),
                ('landbank', models.ImageField(upload_to='images/')),
                ('pnb', models.ImageField(upload_to='images/')),
                ('metro', models.ImageField(upload_to='images/')),
                ('union', models.ImageField(upload_to='images/')),
                ('china', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
