# Generated by Django 4.2.11 on 2024-06-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0025_qrdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
