# Generated by Django 4.2.11 on 2024-06-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0026_mod_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctulogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
