# Generated by Django 5.0.4 on 2024-06-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0026_mod_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='paymaya_number',
        ),
        migrations.AddField(
            model_name='mod',
            name='bank_card',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='mod',
            name='bank_number',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
