# Generated by Django 5.0.4 on 2024-06-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0027_remove_mod_paymaya_number_mod_bank_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='address_volunteer',
        ),
        migrations.AddField(
            model_name='mod',
            name='recepient',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='mod',
            name='recepient_things',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='mod',
            name='what_kind',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
