# Generated by Django 5.0.4 on 2024-06-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0028_remove_mod_address_volunteer_mod_recepient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='bank_card',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mod',
            name='bank_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='mod',
            name='recepient',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mod',
            name='recepient_things',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mod',
            name='what_kind',
            field=models.CharField(max_length=20),
        ),
    ]
