# Generated by Django 5.0.4 on 2024-06-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0029_alter_mod_bank_card_alter_mod_bank_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
