# Generated by Django 5.0.4 on 2024-06-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0030_alter_mod_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='date_sched',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='mod',
            name='recepient',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='mod',
            name='recepient_things',
            field=models.CharField(default='', max_length=20),
        ),
    ]
