# Generated by Django 5.0.4 on 2024-06-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0031_alter_mod_date_sched_alter_mod_recepient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='image_details',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
